package com.lx.activiti.mapper;

import com.lx.activiti.dto.ActIdUser;

public interface ActIdUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbggenerated
     */
    int insert(ActIdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbggenerated
     */
    int insertSelective(ActIdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbggenerated
     */
    ActIdUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActIdUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActIdUser record);
}