package com.lx.activiti.mapper;

import com.lx.activiti.dto.ActIdMembershipKey;

public interface ActIdMembershipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ActIdMembershipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbggenerated
     */
    int insert(ActIdMembershipKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_id_membership
     *
     * @mbggenerated
     */
    int insertSelective(ActIdMembershipKey record);
}