package com.lx.activiti.mapper;

import com.lx.activiti.dto.TLeave;

public interface TLeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    int insert(TLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    int insertSelective(TLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    TLeave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TLeave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_leave
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TLeave record);
}