package com.lx.activiti.dto;

import java.util.Date;

public class TLeave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.leaveDate
     *
     * @mbggenerated
     */
    private Date leavedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.leaveDays
     *
     * @mbggenerated
     */
    private Integer leavedays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.processInstanceId
     *
     * @mbggenerated
     */
    private String processinstanceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_leave.leaveReason
     *
     * @mbggenerated
     */
    private String leavereason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.id
     *
     * @return the value of t_leave.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.id
     *
     * @param id the value for t_leave.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.userId
     *
     * @return the value of t_leave.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.userId
     *
     * @param userid the value for t_leave.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.leaveDate
     *
     * @return the value of t_leave.leaveDate
     *
     * @mbggenerated
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.leaveDate
     *
     * @param leavedate the value for t_leave.leaveDate
     *
     * @mbggenerated
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.leaveDays
     *
     * @return the value of t_leave.leaveDays
     *
     * @mbggenerated
     */
    public Integer getLeavedays() {
        return leavedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.leaveDays
     *
     * @param leavedays the value for t_leave.leaveDays
     *
     * @mbggenerated
     */
    public void setLeavedays(Integer leavedays) {
        this.leavedays = leavedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.state
     *
     * @return the value of t_leave.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.state
     *
     * @param state the value for t_leave.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.processInstanceId
     *
     * @return the value of t_leave.processInstanceId
     *
     * @mbggenerated
     */
    public String getProcessinstanceid() {
        return processinstanceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.processInstanceId
     *
     * @param processinstanceid the value for t_leave.processInstanceId
     *
     * @mbggenerated
     */
    public void setProcessinstanceid(String processinstanceid) {
        this.processinstanceid = processinstanceid == null ? null : processinstanceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_leave.leaveReason
     *
     * @return the value of t_leave.leaveReason
     *
     * @mbggenerated
     */
    public String getLeavereason() {
        return leavereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_leave.leaveReason
     *
     * @param leavereason the value for t_leave.leaveReason
     *
     * @mbggenerated
     */
    public void setLeavereason(String leavereason) {
        this.leavereason = leavereason == null ? null : leavereason.trim();
    }
}